### ISSUE TITLE
homebrew: Calling Formula.sha1 is disabled

### ISSUE THREAD

**Issue by msemple1111** [nwoolls/homebrew-cryptocoin#2]
`Error: Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.`

` /usr/local/Homebrew/Library/Taps/nwoolls/homebrew-cryptocoin/bfgminer.rb:7:in "<class:Bfgminer>"`
`Please report this to the nwoolls/cryptocoin tap!`

iMac 10.10.5  
Homebrew 1.2.1  

Go this issue when running `brew update`

**Comment by nwoolls** [comment]
Use the following repo instead:

* https://github.com/nwoolls/homebrew-xgminer
